### ISSUE TITLE
Clicking into a newly-created pipeline causes the UI to break.

### ISSUE THREAD

**Issue by gtiwillhims** [Yaytay/query-engine#140]
Creating a new pipeline by clicking the burger menu, 'New pipeline' on http://localhost:2000/ui/design. Opening the pipeline breaks the UI.
![image](https://github.com/Yaytay/query-engine/assets/68330774/4070d4df-ed64-4736-8659-626f268b580e)
![image](https://github.com/Yaytay/query-engine/assets/68330774/f94eb313-fea6-4131-8597-a7eaed9d6f6d)

**Comment by Yaytay** [comment]
UI now saves a valid pipeline, but I still don't like that behaviour when it gets something invalid.

**Comment by Yaytay** [comment]
No long errors on loading an empty file.
