### ISSUE TITLE
Cannot error when viewing newly created pipelines.

### ISSUE THREAD

**Issue by gtiwillhims** [Yaytay/query-engine#141]
Creating a new pipeline in http://localhost:2000/ui/design, when the pipeline is created this error occurs:

The file has been saved, but could not be parsed as a Pipeline: No content to map due to end-of-input at [Source: (byte[])""; line: 1, column: 1] (from NoStackTraceThrowable)

The yaml file does appear in the repo. Clicking on the file to open it causes another (potentially related) error which is covered in another ticket.

**Comment by Yaytay** [comment]
UI now saves a valid pipeline.
