### ISSUE TITLE
Blank Columns in Output

### ISSUE THREAD

**Issue by Hamad-R** [Yaytay/query-engine#182]
The lookup columns when not selected are showing up as empty columns in the output

![image](https://github.com/user-attachments/assets/4080b8bc-f75d-4446-b04b-cf9751c71662)

**Comment by Yaytay** [comment]
Both Lookups and Dynamic Fields need help from the query design to prevent this.
For Dynamic Fields the output will include all fields returned by the Field Definition query will be included in the output - so ensure the ones you don't want aren't returned by that query.
For Lookups every defined Lookup Field will be included in the output unless (new feature) the condition on the Lookup Field evaluates to false - so set a suitable condition.
