### ISSUE TITLE
Default Fields and Adding Fields via Parameters

### ISSUE THREAD

**Issue by gtiwillhims** [Yaytay/query-engine#54]
Feeds should be able to be configured such that, by default, a small subset of fields should be provided when a query is run without parameters. Additional fields can then be requested via parameters.

On the UI side, all the possible fields should be visible, such that an end user can click to add them.

The idea being that the laziest option outputs the least possible data. With the current QE, the laziest option ends up with the most data transfer.

This should be the process for all fields, both static and dynamic.

**Comment by Yaytay** [comment]
This is demonstrated in [LookupIT.yaml](https://github.com/Yaytay/query-engine/blob/main/query-engine/src/main/resources/samples/sub1/sub2/LookupIT.yaml).

The Query Engine itself never parses the SQL, so it only knows which fields are in it by executing it - which means it's not possible for it to automatically report the different columns for different arguments.
